version: '3'
services:
  backend:
    container_name: "flask-app-backend"
    image: nahid0002/flask-app:latest
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: "mysql"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_DB: "myDb"
    depends_on:
      - mysql
    networks:
      - two-tier-net


  mysql:
    container_name: "mysql-db"
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: myDb
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_ROOT_PASSWORD : "admin"

    volumes:
      - ./message.sql:/docker-entrypoint-initdb.d/message.sql
      - mysql-data:/var/lib/mysql
    networks:
      - two-tier-net

volumes:
  mysql-data:
networks:
  two-tier-net:
    name: two-tier-net
    driver: bridge